# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#development:
#  adapter: postgresql
#  username: postgres
#  password: srishti
#  host: localhost
#  port: 5433
#  database: sample_prject

development:
  adapter: postgresql
  encoding: unicode
  database: di_development
  pool: 5
  username: davidlee
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: di_test
  pool: 5
  username: davidlee
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: di_production
  pool: 5
  username: user
  password: